/**
 * AI Crowd Density Prediction API Service.
 * Consumes live predictions generated by the trained XGBoost model from FastAPI backend.
 */

export interface PredictionZone {
  zone_id: string;
  zone_name: string;
  predicted_crowd_count: number;
  predicted_density_p_m2: number;
  risk_level: "LOW" | "MODERATE" | "HIGH" | "CRITICAL" | string;
  trend: "increasing" | "decreasing" | "stable" | string;
  confidence_score: number;
}

export interface PredictionResponse {
  timestamp: string;
  prediction_horizon_minutes: number;
  zones: PredictionZone[];
}

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

/**
 * Fetches real-time XGBoost AI crowd density forecasts from FastAPI backend.
 */
export async function fetchPredictions(): Promise<PredictionResponse> {
  const candidateUrls = [
    `${API_BASE_URL}/api/v1/predictions/`,
    `http://localhost:8000/api/v1/predictions/`,
    `/api/v1/predictions/`,
  ];

  let lastError: Error | null = null;

  for (const url of candidateUrls) {
    try {
      const response = await fetch(url, {
        method: "GET",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
      });

      if (response.ok) {
        const data: PredictionResponse = await response.json();
        return data;
      }
    } catch (err) {
      lastError = err instanceof Error ? err : new Error("Network request failed");
    }
  }

  throw lastError || new Error("Failed to connect to AI prediction service backend");
}
