"""initial_database_schema

Revision ID: c49a8408d165
Revises: 
Create Date: 2026-07-26 14:39:45.070431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49a8408d165'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_zone_name'), 'alerts', ['zone_name'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('measurement_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_metric_name'), 'analytics', ['metric_name'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('predicted_density', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_risk_level'), 'predictions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_predictions_zone_name'), 'predictions', ['zone_name'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('travel_time', sa.Float(), nullable=False),
    sa.Column('congestion_level', sa.Float(), nullable=False),
    sa.Column('route_status', sa.Enum('CLEAR', 'MODERATE', 'CONGESTED', 'BLOCKED', name='routestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_route_name'), 'routes', ['route_name'], unique=False)
    op.create_index(op.f('ix_routes_source'), 'routes', ['source'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_name', sa.String(length=100), nullable=False),
    sa.Column('simulation_status', sa.Enum('RUNNING', 'PAUSED', 'STOPPED', 'COMPLETED', 'FAILED', name='simulationstatus'), nullable=False),
    sa.Column('active_agents', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('density_level', sa.String(length=50), nullable=False),
    sa.Column('chokepoints_active', sa.Integer(), nullable=False),
    sa.Column('time_elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_simulation_name'), 'simulations', ['simulation_name'], unique=False)
    op.create_index(op.f('ix_simulations_simulation_status'), 'simulations', ['simulation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_simulation_status'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_simulation_name'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_routes_source'), table_name='routes')
    op.drop_index(op.f('ix_routes_route_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_predictions_zone_name'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_risk_level'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_analytics_metric_name'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_alerts_zone_name'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
